In [2]:
symbols ="$*&!@"
codes=[]
for symbol in symbols:
    codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


In [3]:
symbols ="$*&!@"
codes=[ord(symbol) for symbol in symbols]
print(codes)

[36, 42, 38, 33, 64]


In [4]:
x='"!~$$*&!@'
dummy =  [ord(x) for x in x]
print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [5]:
symbols='"!~$$*&!@'
beyond_ascii=[ord(s) for s in symbols if ord(s)>32]
print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [8]:
symbols='"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c>64,map(ord,symbols)))

print(beyond_ascii,'\n')
print(f"Map function:\n>>> {map(ord,symbols)}")
print(f"List function:\n>>> {list(map(ord,symbols))}")

[126] 

Map function:
>>> <map object at 0x79d42429b550>
List function:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


In [9]:
colors = ['black','white']
sizes=['S','M','L']
tshirts=[(color,size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
  for size in sizes:
    print((color,size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [10]:
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [12]:
colors = ['black','white']
sizes=['S','M','L']

for tshirts in ('{} {}'.format(c,s) for s in sizes for c in colors):
  print(tshirts)

black S
white S
black M
white M
black L
white L


In [20]:
lax_coordinates = (33.9425, -118.408056)
city,year,pop,chg,area =('Tokyo',2003,32450,0.66,8014)
traveler_ids = [('USA','31195855'),
                ('BPA','CE342567'),
                ('ESP','XDA205856')]

for passport in sorted(traveler_ids):
  print('%s/%s' % passport)
  print('{}/{}'.format(passport[0],passport[1]))
  print(f'{passport[0]}/{passport[1]}')



BPA/CE342567
BPA/CE342567
BPA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


In [21]:
for country, _ in traveler_ids:
  print(country)

USA
BPA
ESP


In [22]:
print('%s/%s'%passport)

USA/31195855


In [23]:
lax_coordinates = (33.9425, -118.408056)
latitude,longitude = lax_coordinates
print(latitude)
print(longitude)

33.9425
-118.408056


In [24]:
a=10; b=20
b,a=a,b
print(a,b)

20 10


In [25]:
divmod(20,8)

(2, 4)

In [26]:
t=(20,8)
divmod(*t)

(2, 4)

In [27]:
quotient, remainder=divmod(*t)
quotient, remainder

(2, 4)

In [29]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [30]:
a,b,*rest = range(5)
a,b,rest

(0, 1, [2, 3, 4])

In [31]:
a,b,*rest = range(3)
a,b,rest

(0, 1, [2])

In [32]:
a,b,*rest = range(2)
a,b,rest

(0, 1, [])

In [34]:
a,*body,c,d = range(5)
a,body,c,d

(0, [1, 2], 3, 4)

In [35]:
*head,b,c,d=range(5)
head,b,c,d

([0, 1], 2, 3, 4)

In [44]:
metro_areas = [("Tokyo","JP",36.966,(35,139)),
               ("Delhi NCR","IN",21,(28,77)),
               ("Mexico CIty","MX",20,(19,-99)),
               ("New York-Netwark","US",20,(40,-74)),
               ("Sao Paulo","BR",10,(-23,-46))
               ]

print("{:15}|{:^9}|{:^9}".format('','lat.','long.'))
fmt = '{:15}|{:9.4f}|{:9.4f}'

for name, cc, pop, (lat,longi) in metro_areas:
  if longi<=0:
    print(fmt.format(name,lat,longi))

               |  lat.   |  long.  
Mexico CIty    |  19.0000| -99.0000
New York-Netwark|  40.0000| -74.0000
Sao Paulo      | -23.0000| -46.0000


In [49]:
from collections import namedtuple
City = namedtuple('City','name country population coordinates')
tokyo = City('Tokyo','JP',36.933,(35.689,139,691))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139, 691))

In [50]:
tokyo.population

36.933

In [51]:
tokyo.coordinates

(35.689, 139, 691)

In [52]:
tokyo[1]

'JP'

In [53]:
City._fields
LatLong = namedtuple('LatLong','lat long')
delhi_data = ('Delhi NCR','IN',21.935,LatLong(28.613,77.208))

In [55]:
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613, long=77.208)}

In [56]:
for key,value in delhi._asdict().items():
  print(key+':',value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [57]:
l=[10,20,30,40,50,60]
l[:2]

[10, 20]

In [58]:
l[2:]

[30, 40, 50, 60]

In [59]:
l[:3]

[10, 20, 30]

In [60]:
l[3:]

[40, 50, 60]

In [65]:
invoice = """
0.....6................25........33......40.......
1909  Pimoroni           $17.50    3      $52.50
1489  6mm Tactile         $4.95     2      $9.90
"""
SKU=slice(0,6)
DESCRIPTION=slice(6,25)
UNIT_PRICE=slice(25,33)
QUANTITY=slice(33,40)
ITEM_TOTAL=slice(40,None)

line_items = invoice.split('\n')[2:]
for item in line_items:
  print(item[UNIT_PRICE],item[DESCRIPTION])

$17.50   Pimoroni           
 $4.95   6mm Tactile        
 


In [75]:
l=list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [76]:
l[2:5]=[20,30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [77]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [78]:
l[3::2]=[11,22]
l

[0, 1, 20, 11, 5, 22, 9]

In [79]:
l[2:5]=100

TypeError: must assign iterable to extended slice

In [80]:
l[2:5]=[100]
l

[0, 1, 100, 22, 9]

In [81]:
l=[1,2,3]
l*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [82]:
5*'abcd'

'abcdabcdabcdabcdabcd'

In [85]:
board=[['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [86]:
board[1][2]='X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [90]:
weird_board = [['_']*3]*3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [91]:
weird_board[1][2]='0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [93]:
row =['_']*3
board=[]
for i in range(3):
  board.append(row)
board[1][2]='X'
board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [94]:
row =['_']*3
board=[]
for i in range(3):
  board.append(row)
print(board)
board[2][0]='X'
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['X', '_', '_'], ['X', '_', '_'], ['X', '_', '_']]

In [99]:
l=[1,2,3]
id(l)

133952387762560

In [100]:
l*=2
l

[1, 2, 3, 1, 2, 3]

In [101]:
id(l)

133952387762560

In [102]:
t=(1,2,3)
id(t)

133952040760704

In [103]:
t*=2
id(t)

133952038374176

In [104]:
t= (1,2,[30,40])
print(t)
t[2]+=[50,60]

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [105]:
print(t)

(1, 2, [30, 40, 50, 60])


In [106]:
fruits= ['grape','raspberry','apple','banna']
sorted(fruits)

['apple', 'banna', 'grape', 'raspberry']

In [107]:
fruits

['grape', 'raspberry', 'apple', 'banna']

In [108]:
sorted(fruits,reverse=True)

['raspberry', 'grape', 'banna', 'apple']

In [109]:
sorted(fruits,key=len)

['grape', 'apple', 'banna', 'raspberry']

In [110]:
sorted(fruits,key=len,reverse=True)

['raspberry', 'grape', 'apple', 'banna']

In [111]:
fruits

['grape', 'raspberry', 'apple', 'banna']

In [113]:
fruits.sort()
fruits

['apple', 'banna', 'grape', 'raspberry']

In [114]:
from array import array
from random import random

floats = array('d',(random() for _ in range(10**7)))
floats[-1]

0.048605055180118706

In [115]:
with open('floats.bin','wb') as f:
  floats.tofile(f)

In [120]:
floats2 =array('d')
with open('floats.bin','rb') as f:
  floats2.fromfile(f,10**7)
floats2[-1]

0.048605055180118706

In [118]:
floats==floats2

True

In [125]:
import array
numbers = array.array('h',[-2,-1,0,1,2])
memv = memoryview(numbers)
len(memv)

5

In [126]:
memv[0]

-2

In [129]:
memv_oct=memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [130]:
memv_oct[5]=4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [131]:
data=bytearray(b'hello world')
mv = memoryview(data)

print(mv[0])
mv[0] = 72

print(data)

104
bytearray(b'Hello world')


In [133]:
import numpy
a=numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [134]:
a.shape

(12,)

In [135]:
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
a[2]

array([ 8,  9, 10, 11])

In [137]:
a[2,1]

np.int64(9)

In [138]:
a[:,1]

array([1, 5, 9])

In [140]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])